// <auto-generated />
using System;
using DocumentProcessingAPI.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace DocumentProcessingAPI.Infrastructure.Migrations
{
    [DbContext(typeof(DocumentProcessingDbContext))]
    [Migration("20251021145724_IncreaseAllFieldLengths")]
    partial class IncreaseAllFieldLengths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DocumentProcessingAPI.Core.Entities.Document", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<long>("FileSize")
                        .HasColumnType("bigint");

                    b.Property<string>("OriginalFileName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ProcessingError")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UploadedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("UserId")
                        .HasMaxLength(36)
                        .HasColumnType("character varying(36)");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("IX_Documents_Status");

                    b.HasIndex("UploadedAt")
                        .HasDatabaseName("IX_Documents_UploadedAt");

                    b.HasIndex("UserId")
                        .HasDatabaseName("IX_Documents_UserId");

                    b.HasIndex("UserId", "Status")
                        .HasDatabaseName("IX_Documents_UserId_Status");

                    b.ToTable("Documents", (string)null);
                });

            modelBuilder.Entity("DocumentProcessingAPI.Core.Entities.DocumentChunk", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ChunkSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<Guid>("DocumentId")
                        .HasColumnType("uuid");

                    b.Property<string>("EmbeddingId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EndPosition")
                        .HasColumnType("integer");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<int>("StartPosition")
                        .HasColumnType("integer");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ChunkSequence")
                        .HasDatabaseName("IX_DocumentChunks_ChunkSequence");

                    b.HasIndex("DocumentId")
                        .HasDatabaseName("IX_DocumentChunks_DocumentId");

                    b.HasIndex("EmbeddingId")
                        .HasDatabaseName("IX_DocumentChunks_EmbeddingId");

                    b.HasIndex("PageNumber")
                        .HasDatabaseName("IX_DocumentChunks_PageNumber");

                    b.HasIndex("DocumentId", "ChunkSequence")
                        .IsUnique()
                        .HasDatabaseName("IX_DocumentChunks_DocumentId_ChunkSequence");

                    b.ToTable("DocumentChunks", (string)null);
                });

            modelBuilder.Entity("DocumentProcessingAPI.Core.Entities.Embedding", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("ACL")
                        .HasColumnType("text");

                    b.Property<string>("AllParts")
                        .HasColumnType("text");

                    b.Property<string>("Assignee")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("ChunkContent")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ChunkIndex")
                        .HasColumnType("integer");

                    b.Property<int>("ChunkSequence")
                        .HasColumnType("integer");

                    b.Property<string>("Container")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ContentPreview")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<DateTime?>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DocumentCategory")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("EmbeddingId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<int>("EndPosition")
                        .HasColumnType("integer");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("content_manager_record");

                    b.Property<string>("FileExtension")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FileType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("IndexedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<int>("PageNumber")
                        .HasColumnType("integer");

                    b.Property<string>("RecordTitle")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("RecordType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<long>("RecordUri")
                        .HasColumnType("bigint");

                    b.Property<int>("StartPosition")
                        .HasColumnType("integer");

                    b.Property<int>("TokenCount")
                        .HasColumnType("integer");

                    b.Property<int>("TotalChunks")
                        .HasColumnType("integer");

                    b.Property<Vector>("Vector")
                        .IsRequired()
                        .HasColumnType("vector(3072)");

                    b.HasKey("Id");

                    b.HasIndex("DateCreated")
                        .HasDatabaseName("IX_Embeddings_DateCreated");

                    b.HasIndex("EmbeddingId")
                        .IsUnique()
                        .HasDatabaseName("IX_Embeddings_EmbeddingId");

                    b.HasIndex("EntityType")
                        .HasDatabaseName("IX_Embeddings_EntityType");

                    b.HasIndex("FileType")
                        .HasDatabaseName("IX_Embeddings_FileType");

                    b.HasIndex("RecordType")
                        .HasDatabaseName("IX_Embeddings_RecordType");

                    b.HasIndex("RecordUri")
                        .HasDatabaseName("IX_Embeddings_RecordUri");

                    b.ToTable("Embeddings", (string)null);
                });

            modelBuilder.Entity("DocumentProcessingAPI.Core.Entities.DocumentChunk", b =>
                {
                    b.HasOne("DocumentProcessingAPI.Core.Entities.Document", "Document")
                        .WithMany("Chunks")
                        .HasForeignKey("DocumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Document");
                });

            modelBuilder.Entity("DocumentProcessingAPI.Core.Entities.Document", b =>
                {
                    b.Navigation("Chunks");
                });
#pragma warning restore 612, 618
        }
    }
}
